import type { CollectionDetail } from "./types";

const cover = (file: string, alt: string): CollectionDetail["cover"] => ({
  url: `/images/covers/${file}`,
  alt,
});

export const COLLECTION_DETAIL_STUBS: CollectionDetail[] = [
  {
    id: "dark-side",
    slug: "the-dark-side-of-the-moon",
    title: "The Dark Side of the Moon",
    year: 1973,
    country: "UK",
    duration: "43 min",
    status: "Released",
    artist: "Pink Floyd",
    label: "Harvest",
    shortDescription:
      "A continuous suite of songs about time, money, madness and the quiet pressure of modern life—built on pulse, tape and prism light.",
    editorNote: "Headphones. Lights low. One full side without skipping.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
      { label: "Bandcamp", href: "#" },
    ],
    cover: cover(
      "dark-side-of-the-moon.jpg",
      "Pink Floyd — The Dark Side of the Moon cover",
    ),
    characteristics: {
      oddity: ["Artistic", "Philosophical", "Emotional", "Experimental"],
      meme: ["Cult"],
    },
    categories: {
      genres: ["Progressive Rock", "Art Rock"],
      themes: ["Time", "Madness", "Society"],
      atmosphere: ["Cosmic", "Melancholic"],
      mood: ["Reflective", "Uneasy"],
      tags: ["Concept Album", "Headphones"],
    },
    tracks: [
      { id: "1", title: "Speak to Me", duration: "1:07" },
      { id: "2", title: "Breathe (In the Air)", duration: "2:50" },
      { id: "3", title: "On the Run", duration: "3:45" },
      { id: "4", title: "Time", duration: "6:53" },
      { id: "5", title: "The Great Gig in the Sky", duration: "4:44" },
      { id: "6", title: "Money", duration: "6:23" },
      { id: "7", title: "Us and Them", duration: "7:50" },
      { id: "8", title: "Any Colour You Like", duration: "3:26" },
      { id: "9", title: "Brain Damage", duration: "3:47" },
      { id: "10", title: "Eclipse", duration: "2:12" },
    ],
  },
  {
    id: "kind-of-blue",
    slug: "kind-of-blue",
    title: "Kind of Blue",
    year: 1959,
    country: "USA",
    duration: "46 min",
    status: "Released",
    artist: "Miles Davis",
    label: "Columbia",
    shortDescription:
      "Modal jazz distilled to space and breath—five pieces that still feel like open night air.",
    editorNote: "Play it once through. Let the silence between phrases count.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
    ],
    cover: cover("kind-of-blue.jpg", "Miles Davis — Kind of Blue cover"),
    characteristics: {
      oddity: ["Artistic", "Emotional", "Accessible", "Philosophical"],
      meme: ["Cult"],
    },
    categories: {
      genres: ["Jazz", "Modal Jazz"],
      themes: ["Night", "Space", "Improvisation"],
      atmosphere: ["Cool", "Intimate"],
      mood: ["Calm", "Nostalgic"],
      tags: ["Late Night", "Essential"],
    },
    tracks: [
      { id: "1", title: "So What", duration: "9:22" },
      { id: "2", title: "Freddie Freeloader", duration: "9:46" },
      { id: "3", title: "Blue in Green", duration: "5:37" },
      { id: "4", title: "All Blues", duration: "11:33" },
      { id: "5", title: "Flamenco Sketches", duration: "9:26" },
    ],
  },
  {
    id: "nevermind",
    slug: "nevermind",
    title: "Nevermind",
    year: 1991,
    country: "USA",
    duration: "42 min",
    status: "Released",
    artist: "Nirvana",
    label: "DGC",
    shortDescription:
      "Quiet-loud rupture that dragged underground voltage into the mainstream—and never quite settled after.",
    editorNote: "Start loud. End louder. Skip nothing on side A.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
    ],
    cover: cover("nevermind.jpg", "Nirvana — Nevermind cover"),
    characteristics: {
      oddity: ["Emotional", "Dark", "Chaotic", "Accessible"],
      meme: ["Cult", "Edge"],
    },
    categories: {
      genres: ["Grunge", "Alternative Rock"],
      themes: ["Alienation", "Youth", "Anger"],
      atmosphere: ["Raw", "Suburban"],
      mood: ["Restless", "Cathartic"],
      tags: ["90s", "Anthem"],
    },
    tracks: [
      { id: "1", title: "Smells Like Teen Spirit", duration: "5:01" },
      { id: "2", title: "In Bloom", duration: "4:14" },
      { id: "3", title: "Come as You Are", duration: "3:39" },
      { id: "4", title: "Breed", duration: "3:03" },
      { id: "5", title: "Lithium", duration: "4:17" },
      { id: "6", title: "Polly", duration: "2:57" },
      { id: "7", title: "Territorial Pissings", duration: "2:23" },
      { id: "8", title: "Drain You", duration: "3:43" },
      { id: "9", title: "Lounge Act", duration: "2:36" },
      { id: "10", title: "Stay Away", duration: "3:32" },
      { id: "11", title: "On a Plain", duration: "3:16" },
      { id: "12", title: "Something in the Way", duration: "3:52" },
    ],
  },
  {
    id: "sgt-pepper",
    slug: "sgt-peppers-lonely-hearts-club-band",
    title: "Sgt. Pepper's Lonely Hearts Club Band",
    year: 1967,
    country: "UK",
    duration: "40 min",
    status: "Released",
    artist: "The Beatles",
    label: "Parlophone",
    shortDescription:
      "A studio carnival in costume—pop invention stacked until the album becomes a world of its own.",
    editorNote: "Treat it as one room. Don’t shuffle the first listen.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
    ],
    cover: cover(
      "sgt-pepper.jpg",
      "The Beatles — Sgt. Pepper's Lonely Hearts Club Band cover",
    ),
    characteristics: {
      oddity: ["Artistic", "Experimental", "Funny", "Accessible"],
      meme: ["Cult", "Camp"],
    },
    categories: {
      genres: ["Pop", "Psychedelic Rock"],
      themes: ["Performance", "Identity", "Carnival"],
      atmosphere: ["Technicolor", "Playful"],
      mood: ["Uplifting", "Curious"],
      tags: ["Concept Album", "Studio"],
    },
    tracks: [
      {
        id: "1",
        title: "Sgt. Pepper's Lonely Hearts Club Band",
        duration: "2:02",
      },
      {
        id: "2",
        title: "With a Little Help from My Friends",
        duration: "2:44",
      },
      { id: "3", title: "Lucy in the Sky with Diamonds", duration: "3:28" },
      { id: "4", title: "Getting Better", duration: "2:48" },
      { id: "5", title: "Fixing a Hole", duration: "2:36" },
      { id: "6", title: "She's Leaving Home", duration: "3:35" },
      {
        id: "7",
        title: "Being for the Benefit of Mr. Kite!",
        duration: "2:37",
      },
      { id: "8", title: "Within You Without You", duration: "5:05" },
      { id: "9", title: "When I'm Sixty-Four", duration: "2:37" },
      { id: "10", title: "Lovely Rita", duration: "2:42" },
      { id: "11", title: "Good Morning Good Morning", duration: "2:41" },
      {
        id: "12",
        title: "Sgt. Pepper's Lonely Hearts Club Band (Reprise)",
        duration: "1:19",
      },
      { id: "13", title: "A Day in the Life", duration: "5:39" },
    ],
  },
  {
    id: "crimson-king",
    slug: "in-the-court-of-the-crimson-king",
    title: "In the Court of the Crimson King",
    year: 1969,
    country: "UK",
    duration: "44 min",
    status: "Released",
    artist: "King Crimson",
    label: "Island",
    shortDescription:
      "Prog’s founding omen—fractured court music where jazz, rock and dread share the same throne.",
    editorNote: "Loud enough to feel the reed. Quiet enough to hear the fear.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
    ],
    cover: cover(
      "crimson-king.jpg",
      "King Crimson — In the Court of the Crimson King cover",
    ),
    characteristics: {
      oddity: ["Experimental", "Dark", "Artistic", "Chaotic"],
      meme: ["Cult", "Edge"],
    },
    categories: {
      genres: ["Progressive Rock"],
      themes: ["Power", "Chaos", "Myth"],
      atmosphere: ["Theatrical", "Uneasy"],
      mood: ["Intense", "Ominous"],
      tags: ["Debut", "Prog"],
    },
    tracks: [
      { id: "1", title: "21st Century Schizoid Man", duration: "7:24" },
      { id: "2", title: "I Talk to the Wind", duration: "6:05" },
      { id: "3", title: "Epitaph", duration: "8:47" },
      { id: "4", title: "Moonchild", duration: "12:13" },
      {
        id: "5",
        title: "The Court of the Crimson King",
        duration: "9:25",
      },
    ],
  },
  {
    id: "aladdin-sane",
    slug: "aladdin-sane",
    title: "Aladdin Sane",
    year: 1973,
    country: "UK",
    duration: "41 min",
    status: "Released",
    artist: "David Bowie",
    label: "RCA",
    shortDescription:
      "Ziggy on the road through America—glam lightning, piano fractures and a face split by a bolt.",
    editorNote:
      "Watch the makeup, listen to the piano. Both are the character.",
    availability: [
      { label: "Spotify", href: "#" },
      { label: "Apple Music", href: "#" },
    ],
    cover: cover("aladdin-sane.jpg", "David Bowie — Aladdin Sane cover"),
    characteristics: {
      oddity: ["Artistic", "Weird", "Emotional", "Experimental"],
      meme: ["Cult", "Camp"],
    },
    categories: {
      genres: ["Glam Rock", "Art Rock"],
      themes: ["Identity", "America", "Fame"],
      atmosphere: ["Electric", "Theatrical"],
      mood: ["Restless", "Seductive"],
      tags: ["Iconic Cover", "70s"],
    },
    tracks: [
      { id: "1", title: "Watch That Man", duration: "4:30" },
      { id: "2", title: "Aladdin Sane (1913-1938-197?)", duration: "5:06" },
      { id: "3", title: "Drive-In Saturday", duration: "4:33" },
      { id: "4", title: "Panic in Detroit", duration: "4:25" },
      { id: "5", title: "Cracked Actor", duration: "3:01" },
      { id: "6", title: "Time", duration: "5:09" },
      { id: "7", title: "The Prettiest Star", duration: "3:31" },
      { id: "8", title: "Let's Spend the Night Together", duration: "3:10" },
      { id: "9", title: "The Jean Genie", duration: "4:07" },
      { id: "10", title: "Lady Grinning Soul", duration: "3:54" },
    ],
  },
];

export const getCollectionDetailBySlug = (
  slug: string,
): CollectionDetail | undefined =>
  COLLECTION_DETAIL_STUBS.find((item) => item.slug === slug);
