import type { AdminProfile } from "./types";

/** Curator desk stubs — layout only, no CMS. */
export const ADMIN_PROFILE_STUB: AdminProfile = {
  role: "CURATOR",
  established: "2026",
  cards: [
    {
      id: "1",
      slug: "blade-runner-2049",
      title: "Blade Runner 2049",
      credit: "Denis Villeneuve",
      type: "movie",
      year: 2017,
      country: "USA",
      shortDescription:
        "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
      imageUrl: "https://picsum.photos/seed/bladerunner2049/600/900",
      aspect: "portrait",
      publishStatus: "draft",
    },
    {
      id: "2",
      slug: "inland-empire",
      title: "Inland Empire",
      credit: "David Lynch",
      type: "movie",
      year: 2006,
      country: "USA",
      shortDescription:
        "As an actress begins to adopt the persona of her character in a film, her world becomes nightmarish and surreal.",
      imageUrl: "https://picsum.photos/seed/inlandempire/600/900",
      aspect: "portrait",
      publishStatus: "draft",
    },
    {
      id: "3",
      slug: "the-queen-is-dead",
      title: "The Queen Is Dead",
      credit: "The Smiths",
      type: "album",
      year: 1986,
      country: "UK",
      shortDescription:
        "The Smiths' third studio album — melancholic indie anthems wrapped in jangle and wit.",
      imageUrl: "/images/covers/sgt-pepper.jpg",
      aspect: "square",
      publishStatus: "public",
    },
    {
      id: "4",
      slug: "twin-peaks-fire-walk-with-me",
      title: "Twin Peaks: Fire Walk With Me",
      credit: "David Lynch",
      type: "movie",
      year: 1992,
      country: "USA",
      shortDescription:
        "A feature film prequel to the Twin Peaks series, focusing on the last days of Laura Palmer.",
      imageUrl: "https://picsum.photos/seed/firewalkwithme/600/900",
      aspect: "portrait",
      publishStatus: "public",
    },
    {
      id: "5",
      slug: "aladdin-sane",
      title: "Aladdin Sane",
      credit: "David Bowie",
      type: "album",
      year: 1973,
      country: "UK",
      shortDescription:
        "Bowie's lightning-bolt glam statement — Ziggy in America.",
      imageUrl: "/images/covers/aladdin-sane.jpg",
      aspect: "square",
      publishStatus: "public",
    },
    {
      id: "6",
      slug: "kind-of-blue",
      title: "Kind of Blue",
      credit: "Miles Davis",
      type: "album",
      year: 1959,
      country: "USA",
      shortDescription: "Modal jazz landmark — cool, spacious, definitive.",
      imageUrl: "/images/covers/kind-of-blue.jpg",
      aspect: "square",
      publishStatus: "draft",
    },
    {
      id: "7",
      slug: "dark-side-of-the-moon",
      title: "The Dark Side of the Moon",
      credit: "Pink Floyd",
      type: "album",
      year: 1973,
      country: "UK",
      shortDescription: "Prism, pulse, and the machine — Floyd's peak.",
      imageUrl: "/images/covers/dark-side-of-the-moon.jpg",
      aspect: "square",
      publishStatus: "public",
    },
  ],
};
